### ISSUE TITLE
Indentation problems in master branch (and probably others)

### ISSUE THREAD

**Issue by wangziqi2013** [sfu-natlang/glm-parser#17]
We observed an indentation problem in data_pool.py, get_next_data(). The return statement should not be under the innermost if block, and should be move one level up.

Also there might be an omit of character "0" in that if statement. Please check your branch accordingly

This issue has been fixed in 3rd_order_feature branch

**Comment by wangziqi2013** [comment]
Please refer to this commit:

https://github.com/sfu-natlang/glm-parser/commit/666f9950824bb0dac91ff387761abc41604170c1

**Comment by anoopsarkar** [comment]
@wangziqi2013 can you please modify master to fix this bug. others can pull from master to fix their branches.

**Comment by wangziqi2013** [comment]
@anoopsarkar Done

And to others @Silveryfu  @sunyans  @RahulRavindren  Please check the latest commit in master branch and fix your branch

**Comment by anoopsarkar** [comment]
Thanks! we can close this issue I assume.
