### ISSUE TITLE
learnerValue is not always defined in glm_parser.py

### ISSUE THREAD

**Issue by avacariu** [sfu-natlang/glm-parser#39]
In `glm_parser.py`, if `sys.argv[1]` is not a file, and `--learner` is not used, then `learnerValue` never gets defined, but it still gets used on line 401 or 403 in
```
learner = get_class_from_module('sequential_learn', 'learn', learnerValue)
```
So you get a `NameError`.

**Comment by jeticg** [comment]
My bad.
