### ISSUE TITLE
glm_parser.py may try to read config from unintended file

### ISSUE THREAD

**Issue by avacariu** [sfu-natlang/glm-parser#40]
If the user accidentally* created a file called (e.g.) `-i`, the code will try to read from that (probably empty) file instead of parsing it as a flag.

I think the safest solution would be to get the config file path passed in using a parameter like `--config` because then we can warn the user that the file doesn't exist and there's also no ambiguity about what they meant.

\* it's _very_ unlikely, but still a possibility if you do stuff like `:w -i` because you didn't properly hit ENTER after the `w`

**Comment by Travelinglight** [comment]
@jeticg  And we can also use `argparse` instead of manually parsing the arguments

**Comment by jeticg** [comment]
@Travelinglight I'll look into `argparse` right now and get back to you

**Comment by jeticg** [comment]
@Travelinglight OK. I think unless there is a bug involved, I don't see the real need of needing to change our current manual operation to using `argparse`.

**Comment by jeticg** [comment]
@avacariu I added a piece of code to see if the config file is indeed a config file by checking the suffix. This is the simplest solution to the problem I think.

**Comment by avacariu** [comment]
> I think unless there is a bug involved, I don't see the real need of needing to change our current manual operation to using argparse.

Using `argparse` will help prevent bugs, and it'll also

* automatically generate help/usage messages so people don't need to remember to update it (e.g. the config file stuff is currently not mentioned in the `HELP_MSG`)
* automatically assign parameters to variables
* automatically check types and coerce them as needed with good error messages for the user
* allow specifying explicit defaults (so #39 doesn't happen again)
* allow repeated arguments (e.g. `-vvvv` for increasing verbosity)

And it's just overall more pythonic than `getopt` (which is probably only in the standard library for backwards compatibility)

**Comment by jeticg** [comment]
OK, I'll see to it after the football match between Germany and Poland. Only less than 30 mins left.

**Comment by jeticg** [comment]
I have performed a dozen tests, but I do not possess the confidence of declaring this fix to be bug free.

**Comment by avacariu** [comment]
This looks pretty good. Only issue I see is the repetition when dealing with overriding variables or defaults. I haven't tried it, but maybe something like this would work?
- put all parameters into a `dict` with the defaults as values (call it `config` or something)
- add the defaults to the arg parser as `arg_parser.set_defaults(**config)` (which should save a bit of typing)
- use same dict to set the defaults in the config parser: `SafeConfigParser(config)`
- store the stuff you get from the config file back into `config`
- override the config file with the `arg_parser` stuff using `config.update(vars(args))`
- then you can call `GlmParser(**config)`

This would require consistent naming of parameters, but I think that's a good thing to have anyways.

**Comment by jeticg** [comment]
I'll look into it when I get back.

**Comment by anoopsarkar** [comment]
I notice some commits against this issue. Is it ready to be closed?

**Comment by jeticg** [comment]
Not yet. Andrei is still working on some improvements I think.

**Comment by avacariu** [comment]
Yeah, I'm working on this. I've just been busy with LensingWikipedia. I'll close it when it's done.

**Comment by anoopsarkar** [comment]
no worries. I noticed some commits so I thought it was done.

**Comment by avacariu** [comment]
I cleaned up glm_parser.py to handle option defaults and parameter names consistently and clearly in this commit: https://github.com/avacariu/glm-parser/commit/d13b42d1a3569b0b4d6e8cce8f8566e964e5c66f

I'll let @jeticg grab stuff from there if he wants since that commit will now conflict with his commits from the last couple days.

**Comment by jeticg** [comment]
@avacariu I'll get to work tonight.

**Comment by avacariu** [comment]
I'll just close this since the original bug is probably gone by now.
