### ISSUE TITLE
ValueError: DATAPREP [ERROR]: source directory do not exist

### ISSUE THREAD

**Issue by avacariu** [sfu-natlang/glm-parser#43]
I'm trying to run `glm_parser.py` using `UD_Czech.config` (no other parameters), and getting the exception in the title.

Shouldn't that directory get created if it's non-existent?

**Comment by jeticg** [comment]
This is probably because you didn't set the environment variable NATLANG_DATA so the DataPrep cannot find the training data.

**Comment by avacariu** [comment]
It doesn't say I have to do that anywhere...

What should it be set to?

**Comment by jeticg** [comment]
You can checkout the readme file for more info. Because we might put the data to different directories, the provided configs all uses the environment variable to find the data. For example your data are under ~Data/glm-parser-data/CoNLL-X, you need to set NATLANG_DATA to ~/Data/

**Comment by avacariu** [comment]
Why does it assume by data is in a directory called `glm-parser-data`?

**Comment by jeticg** [comment]
Right, I should probably change this. The reason why we were using this is because last semester we all put our data under ~/data/glm-parser-data/

**Comment by jeticg** [comment]
I shall now close this issue because it's not an issue

**Comment by avacariu** [comment]
Not giving a proper error message _is_ an issue.

**Comment by jeticg** [comment]
Actually this is the proper error message, it means the data source path specified in the config file do not exist.

**Comment by jeticg** [comment]
Or maybe, instead of checking the directory's existence in DataPrep, we could do a check when reading the config file.

**Comment by avacariu** [comment]
Both should probably be done. Someone using this project as a library should get an exception, but someone running `glm_parser.py` as a program should get a proper* error message.

\* "proper" meaning an error message saying exactly what the error is and how to fix it.

**Comment by jeticg** [comment]
I have add the check data_path code into GlmParser. It will only work in non-yarn mode, because sparkContext cannot check if a directory exists or not. I have not yet found a work around method. According to google, more HDFS operations will only be supported in spark 2.0.

**Comment by jeticg** [comment]
Closing this issue for it has been resolved.
